---
# file: roles/common/defaults/main.yml
proxy_env:
  no_proxy: '*'
#  http_proxy: http://172.16.111.1:8080
#  https_proxy: http://172.16.111.1:8080
#rhel_subscription:
#  username: 'username'
#  password: 'password'
#  pool: 'pool'
#ntp_server: 172.16.111.1
grub_cfg_uefi: "/boot/efi/EFI/{{ ansible_distribution|lower }}/grub.cfg"
grub_cfg_legacy: "/boot/grub2/grub.cfg"
#kdump_partition: "/dump"
kdump_path: "/var/crash"
#common_user:
#  # user/password="hidepin/hidepin123"
#  - { name: 'hidepin', password: '$1$SomeSalt$buSRLdQkj4QgWzx.tbjqv1', uid: '1000', group: 'hidepin', gid: '1000' }
limits_setting:
  - { domain: 'root', type: 'soft', item: 'nofile', value: '65536' }
  - { domain: 'root', type: 'hard', item: 'nofile', value: '65536' }
#  - { domain: 'tomcat8', type: 'soft', item: 'nofile', value: '65536' }
#  - { domain: 'tomcat8', type: 'hard', item: 'nofile', value: '65536' }
#  - { domain: 'tomcat8', type: 'soft', item: 'nproc', value: '8192' }
#  - { domain: 'tomcat8', type: 'hard', item: 'nproc', value: '8192' }
#  - { domain: 'jboss6', type: 'soft', item: 'nofile', value: '65536' }
#  - { domain: 'jboss6', type: 'hard', item: 'nofile', value: '65536' }
#  - { domain: 'jboss6', type: 'soft', item: 'nproc', value: '8192' }
#  - { domain: 'jboss6', type: 'hard', item: 'nproc', value: '8192' }

