---
# file: roles/common/tasks/main.yml
- name: packages install
  yum: name="{{ item }}" state=present
  with_items:
    - openssh-clients
    - libselinux-python

- name: disable selinux
  shell: setenforce Permissive
  when: ansible_selinux.status is undefined or ansible_selinux.status != "disabled"

- block:
  - name: disable selinux setting
    lineinfile: >
      dest=/etc/selinux/config
      regexp='^SELINUX=.*'
      line="SELINUX=disabled"
      state=present
      backup=true
    register: is_selinux_setting

  - name: generate hosts files
    lineinfile: >
      dest=/etc/hosts
      regexp='^{{ item }}.*'
      line="{{ item }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
      state=present
      backup=true
    when: hostvars[item].ansible_fqdn is defined
    register: is_hosts_setting
    with_items: "{{ groups['all'] }}"

  always:
  - name: backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_hosts_setting.results|default() }}"
      - "{{ is_selinux_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: Add common group
  group: >
    name="{{ item.group }}"
    gid="{{ item.gid }}"
  with_items: "{{ common_user }}"
  when: common_user is defined and common_user != None

- name: Add common user
  user: >
    name="{{ item.name }}"
    password="{{ item.password }}"
    uid="{{ item.uid }}"
    group="{{ item.group }}"
    comment="{{ item.name }}"
  with_items: "{{ common_user }}"
  when: common_user is defined and common_user != None

- name: RHEL6 family only setting
  include: rhel6_family.yml
  when: ansible_distribution_major_version == '6'

- name: RHEL7 family only setting
  include: rhel7_family.yml
  when: ansible_distribution_major_version == '7'

- name: reboot after change selinux
  include: reboot.yml
  when: ansible_selinux.status is undefined or ansible_selinux.status != "disabled"
