---
# file: roles/common/tasks/rhel7_family.yml
- name: rhel subscription
  redhat_subscription: >
    state=present
    username="{{ rhel_subscription.username|default() }}"
    password="{{ rhel_subscription.password|default() }}"
    pool="{{ rhel_subscription.pool|default() }}"
    autosubscribe=yes
  when: ansible_distribution == "RedHat" and rhel_subscription is defined

- name: (rhel7 family) runlevel check
  command: systemctl get-default
  register: runlevel
  changed_when: false

- name: (rhel7 family) set multi-user.target
  command: systemctl set-default multi-user.target
  when: runlevel.stdout == "multi-user.targt"

- name: (rhel7 family) disable firewalld services
  systemd: name=firewalld.service enabled=no state=stopped

- block:
  - name: (rhel7 family) chrony packages install
    yum: name=chrony state=present
    when: ntp_server is defined

  - name: (rhel7 family) chrony.conf settings
    template: >
      src=chrony.conf.j2
      dest=/etc/chrony.conf
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_chrony_conf_setting
    when: ntp_server is defined
    notify: chronyd restart

  - name: (rhel7 family) enable chronyd services
    systemd: name=chronyd enabled=yes
    when: ntp_server is defined

  - name: (rhel7 family) journald.conf settings
    ini_file: >
      dest=/etc/systemd/journald.conf
      section=Journal
      option={{ item.option }}
      value={{ item.value }}
      no_extra_spaces=true
      backup=yes
    with_items:
      - { option: 'Storage', value: 'persistent' }
      - { option: 'RateLimitInterval', value: '0s' }
      - { option: 'SystemMaxFileSize', value: '200M' }
      - { option: 'MaxRetentionSec', value: '100day' }
      - { option: 'MaxFileSec', value: '1day' }
    register: is_journald_setting
    notify: systemd-journald restart

  - name: (rhel7 family) rsyslog.conf settings
    copy: >
      src=rsyslog.conf
      dest=/etc/rsyslog.conf
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_rsyslog_setting
    notify: rsyslog restart

  - name: (rhel7 family) abrt check
    stat: path=/etc/abrt/abrt.conf
    register: abrt_conf

  - name: (rhel7 family) abrt.conf settings
    lineinfile: >
      dest=/etc/abrt/abrt.conf
      regexp="^{{ item.option }} =.*"
      line="{{ item.option }} = {{ item.value }}"
      state=present
      backup=yes
    with_items:
      - { option: 'MaxCrashReportsSize', value: '0' }
    register: is_abrt_conf_setting
    when: abrt_conf.stat.exists
    notify: abrtd restart

  - name: (rhel7 family) abrt-action-save-package-data.conf settings
    lineinfile: >
      dest=/etc/abrt/abrt-action-save-package-data.conf
      regexp="^{{ item.option }} =.*"
      line="{{ item.option }} = {{ item.value }}"
      state=present
      backup=yes
    with_items:
      - { option: 'OpenGPGCheck', value: 'no' }
      - { option: 'ProcessUnpackaged', value: 'yes' }
    register: is_abrt_action_setting
    when: abrt_conf.stat.exists
    notify: abrtd restart

  - name: (rhel7 family) bios check
    shell: "[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS"
    register: bios_mode
    changed_when: false

  - name: (rhel7 family) grub settings (kdump and disable ipv6)
    copy: >
      src=etc_default_grub
      dest=/etc/default/grub
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_grub_setting

  - name: grub reconfig
    command: >
      grub2-mkconfig -o
      {{ (bios_mode.stdout == "UEFI")|ternary(grub_cfg_uefi, grub_cfg_legacy) }}
    when: is_grub_setting|changed

  - name: (rhel7 family) check kdump partition
    shell: cat /etc/fstab | grep "{{ kdump_partition }}" | sed 's/^UUID=\([^ ]*\).*/\1/'
    register: kdump_partition_uuid
    changed_when: false
    when: kdump_partition is defined

  - name: (rhel7 family) create kdump dir
    file: >
      path="{{kdump_partition}}{{kdump_path}}"
      state=directory
      recurse=yes
      owner=root
      group=root
      mode=0755
    when: kdump_partition_uuid.stdout is defined

  - name: (rhel7 family) kdump.conf settings
    template: >
      src=kdump.conf.j2
      dest=/etc/kdump.conf
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_kdump_setting
    when: kdump_partition_uuid.stdout is defined
    notify: kdump restart

  - name: (rhel7 family) enable kdump services
    service: name=kdump.service enabled=yes
    when: kdump_partition_uuid.stdout is defined

  - name: (rhel7 family) ulimits settings
    lineinfile: >
      dest=/etc/security/limits.conf
      regexp="^{{ item.domain }}        {{ item.type }}    {{ item.item }}"
      line="{{ item.domain }}        {{ item.type }}    {{ item.item }}           {{ item.value }}"
      state=present
      backup=yes
    with_items: "{{limits_setting}}"
    register: is_limits_setting

  always:
  - name: (rhel7 family) backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_chrony_conf_setting|default() }}"
      - "{{ is_journald_setting.results|default() }}"
      - "{{ is_rsyslog_setting|default() }}"
      - "{{ is_abrt_conf_setting.results|default() }}"
      - "{{ is_abrt_action_setting.results|default() }}"
      - "{{ is_grub_setting|default() }}"
      - "{{ is_kdump_setting|default() }}"
      - "{{ is_limits_setting.results|default() }}"
    loop_control:
      loop_var: backup_item

- name: reboot after kdump setting
  include: reboot.yml
  when: is_grub_setting|changed
